name: yandex_smart_captcha
description: Unofficial Flutter package for Yandex SmartCaptcha with a streamlined API.
version: 7.1.0
homepage: https://github.com/yom-ko/yandex-smart-captcha
repository: https://github.com/yom-ko/yandex-smart-captcha

topics:
  - smart-captcha
  - invisible-captcha
  - recaptcha
  - captcha
  - yandex

screenshots:
  - description: 'This screenshot shows the initial state of the Yandex SmartCaptcha pop-up, featuring a challenge for the user to solve.'
    path: assets/images/screen_2.webp

platforms:
  android:
  ios:

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
