name: yandex_smart_captcha
description: Unofficial Flutter package for Yandex SmartCaptcha with a streamlined API.
version: 3.1.9
homepage: https://github.com/yom-ko/yandex-smart-captcha
repository: https://github.com/yom-ko/yandex-smart-captcha

topics:
  - smart-captcha
  - invisible-captcha
  - recaptcha
  - captcha
  - yandex

screenshots:
  - description: 'This screenshot shows the initial state of the Yandex SmartCaptcha container with the "I’m not a robot" checkbox.'
    path: assets/images/screen_1.webp
  - description: 'This screenshot shows the initial state of the Yandex SmartCaptcha pop-up, featuring a challenge for the user to solve.'
    path: assets/images/screen_2.webp
  - description: 'This screenshot shows the state of the Yandex SmartCaptcha container with the "I’m not a robot" box checked, after the user successfully solved the challenge.'
    path: assets/images/screen_3.webp
  - description: 'This screenshot shows the initial state of the Yandex SmartCaptcha container with the "I’m not a robot" checkbox, as seen in a real-world application.'
    path: assets/images/screen_laz_1.webp
  - description: 'This screenshot shows the initial state of the Yandex SmartCaptcha pop-up, featuring a challenge for the user to solve in a real-world application.'
    path: assets/images/screen_laz_2.webp

platforms:
  android:
  ios:

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
